# Generated by Django 4.2.6 on 2023-10-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0001_initial"),
        ("recipe", "0002_recipe_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredient",
            field=models.ManyToManyField(to="ingredient.ingredient"),
        ),
    ]
